services:
  - type: web
    name: knowyourmpza-api
    runtime: docker
    repo: https://github.com/Mahlatse32/KnowYourMPZA
    branch: main
    rootDir: backend
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGIN
        value: https://knowyourmpza.vercel.app
      - key: INGESTION_ENABLED
        value: "false"
      - key: AI_API_KEY
        sync: false
      - key: AI_MODEL
        value: gpt-5-mini
      - key: AI_BASE_URL
        value: https://api.openai.com/v1
      - key: AI_APP_URL
        value: https://knowyourmpza.vercel.app
      - key: AI_APP_TITLE
        value: KnowYourMPZA
