#!/usr/bin/env python3
"""Create or update a GitHub issue when an ingestion brief is red."""

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any
from urllib.error import HTTPError
from urllib.parse import quote, urlencode
from urllib.request import Request, urlopen

ISSUE_TITLE = "Automated ingestion alert: red brief"
ISSUE_LABELS = ["automation", "ingestion", "needs-attention"]
LABEL_COLORS = {"automation": "1d76db", "ingestion": "0e8a16", "needs-attention": "d93f0b"}

DATABASE_URL_RE = re.compile(r"(?i)\bDATABASE_URL\b\s*[:=]\s*[^\s,;]+")
URL_CREDENTIALS_RE = re.compile(r"(?i)([a-z][a-z0-9+.-]*://)[^/\s:@]+:[^/\s@]+@")
SECRET_RE = re.compile(
    r"(?i)\b(password|passwd|pwd|secret|token|api[_-]?key|access[_-]?key)\b"
    r"(\s*[:=]\s*)([^\s,;]+)"
)
TOKEN_RE = re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,})\b")


def redact_text(value: str) -> str:
    value = DATABASE_URL_RE.sub("DATABASE_URL=[REDACTED]", value)
    value = URL_CREDENTIALS_RE.sub(r"\1[REDACTED]@", value)
    value = SECRET_RE.sub(r"\1\2[REDACTED]", value)
    return TOKEN_RE.sub("[REDACTED]", value)


def redact(value: Any) -> Any:
    if isinstance(value, str):
        return redact_text(value)
    if isinstance(value, list):
        return [redact(item) for item in value]
    if isinstance(value, dict):
        return {key: redact(item) for key, item in value.items()}
    return value


def _markdown(value: Any) -> list[str]:
    if value is None or value == []:
        return ["- None"]
    if isinstance(value, list):
        return [f"- {json.dumps(item, ensure_ascii=True) if isinstance(item, dict) else item}" for item in value]
    if isinstance(value, dict):
        return [f"```json\n{json.dumps(value, indent=2, ensure_ascii=True)}\n```"]
    return [f"- {value}"]


def build_issue_body(brief: dict[str, Any]) -> str:
    safe = redact(brief)
    actions = safe.get("next_recommended_actions", safe.get("next_actions"))
    sections = [
        ("Status", safe.get("status")),
        ("Reasons", safe.get("reasons")),
        ("Attention required", safe.get("attention_required")),
        ("Next recommended actions", actions),
        ("Errors", safe.get("errors")),
        ("Timestamp", safe.get("timestamp")),
    ]
    lines = ["This issue is maintained automatically from the latest red ingestion brief.", ""]
    for heading, value in sections:
        lines.extend([f"## {heading}", *_markdown(value), ""])
    lines.append("_Generated by `backend/scripts/escalate_ingestion_brief.py`._")
    return "\n".join(lines)


class GitHubClient:
    def __init__(self, token: str) -> None:
        self.token = token

    def _request(self, method: str, path: str, payload: dict | None = None) -> Any:
        request = Request(
            f"https://api.github.com{path}",
            data=json.dumps(payload).encode() if payload is not None else None,
            method=method,
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {self.token}",
                "User-Agent": "KnowYourMPZA-ingestion-alert",
                "X-GitHub-Api-Version": "2022-11-28",
                "Content-Type": "application/json",
            },
        )
        try:
            with urlopen(request, timeout=20) as response:
                return json.loads(response.read().decode())
        except HTTPError as exc:
            detail = exc.read().decode(errors="replace")
            raise RuntimeError(f"GitHub API request failed ({exc.code}): {redact_text(detail)}") from exc

    def _ensure_labels(self, repo: str) -> None:
        owner, name = repo.split("/", 1)
        path = f"/repos/{quote(owner)}/{quote(name)}/labels"
        for label in ISSUE_LABELS:
            try:
                self._request("POST", path, {"name": label, "color": LABEL_COLORS[label]})
            except RuntimeError as exc:
                if "(422)" not in str(exc):
                    raise

    def upsert_issue(self, repo: str, title: str, body: str, labels: list[str]) -> dict[str, str]:
        owner, name = repo.split("/", 1)
        self._ensure_labels(repo)
        query = urlencode({"state": "open", "per_page": 100})
        issues = self._request("GET", f"/repos/{quote(owner)}/{quote(name)}/issues?{query}")
        existing = next(
            (issue for issue in issues if "pull_request" not in issue and issue.get("title") == title),
            None,
        )
        payload = {"title": title, "body": body, "labels": labels}
        if existing:
            issue = self._request(
                "PATCH", f"/repos/{quote(owner)}/{quote(name)}/issues/{existing['number']}", payload
            )
            result = "updated_issue"
        else:
            issue = self._request("POST", f"/repos/{quote(owner)}/{quote(name)}/issues", payload)
            result = "created_issue"
        return {"result": result, "issue_url": issue.get("html_url", "")}


def process_brief(
    brief_path: Path,
    repo: str | None,
    dry_run: bool,
    github_client: Any | None = None,
) -> tuple[dict[str, Any], int]:
    try:
        brief = json.loads(brief_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {"result": "error", "error": f"brief not found: {brief_path}"}, 2
    except (json.JSONDecodeError, OSError) as exc:
        return {"result": "error", "error": f"could not read brief: {redact_text(str(exc))}"}, 2

    status = str(brief.get("status", "")).strip().lower()
    if status in {"green", "yellow"}:
        return {"result": "no_escalation", "status": status}, 0
    if status != "red":
        return {"result": "error", "error": f"unsupported brief status: {status or '(missing)'}"}, 2

    issue = {"title": ISSUE_TITLE, "body": build_issue_body(brief), "labels": ISSUE_LABELS, "repo": repo}
    if dry_run:
        return {"result": "planned_issue", "issue": issue}, 0
    if not repo or "/" not in repo:
        return {"result": "error", "error": "--repo owner/name is required for real issue creation"}, 2

    client = github_client
    if client is None:
        token = os.environ.get("GITHUB_TOKEN")
        if not token:
            return {"result": "error", "error": "GITHUB_TOKEN is required for real issue creation"}, 2
        client = GitHubClient(token)
    try:
        return client.upsert_issue(repo, ISSUE_TITLE, issue["body"], ISSUE_LABELS), 0
    except Exception as exc:
        return {"result": "error", "error": redact_text(str(exc))}, 2


def main() -> int:
    parser = argparse.ArgumentParser(description="Escalate a red ingestion brief to GitHub Issues.")
    parser.add_argument("--brief-path", default="reports/ingestion_brief.json")
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY"))
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--json-output", action="store_true")
    args = parser.parse_args()
    result, exit_code = process_brief(Path(args.brief_path), args.repo, args.dry_run)
    if args.json_output:
        print(json.dumps(redact(result), ensure_ascii=True))
    elif result["result"] == "no_escalation":
        print("no_escalation")
    elif result["result"] == "planned_issue":
        print(f"planned_issue: {result['issue']['title']}")
    elif result["result"] in {"created_issue", "updated_issue"}:
        print(f"{result['result']}: {result.get('issue_url', '')}")
    else:
        print(f"error: {result.get('error', 'unknown error')}", file=sys.stderr)
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
